include:
  - board: akdk_bt1
    shield: omega_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: omega_right
    snippet: studio-rpc-ble
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: akdk_bt1
    shield: settings_reset
