#pragma once

#define EE_HANDS
#define VIAL_KEYBOARD_UID {0xf7, 0x7e, 0xbc, 0x83, 0xd4, 0xee, 0x51, 0x88}
#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define PICO_FLASH_SIZE_BYTES (1 * 1024 * 1024)
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_INVERT_X_RIGHT
#define POINTING_DEVICE_INVERT_Y_RIGHT