CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_POINTING=y
CONFIG_PAW3222=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# 1. Bluetoothの通信間隔を限界まで狭めてレスポンスを最速にする（7.5ms間隔）
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6

# マウスの移動レポートの間隔（ミリ秒）を設定してパケットの過剰送信を抑える（例: 10ms〜16ms程度に間引く）
CONFIG_ZMK_POINTING_TICK_DURATION=12
